### ISSUE TITLE
How was RadChar exactly generated?

### ISSUE THREAD

**Issue by bartmch** [abcxyzi/RadChar#2]
I read your article with great interest. Would it be possible to describe how exactly you generated the dataset? Unfortunately I could only find a broad reference to a textbook "Radar Signals". Would it be possible to share some scripts that generated RadChar. Thank you

**Comment by abcxyzi** [comment]
Hi @bartmch, thanks for your interest! Unfortunately, we won't be able to release the scripts used to generate the data due to commercial sensitivity. However, I can point you to some useful resources, such as Levanon's publication, Chapters 4 and 6 are particularly relevant to this work. Our radar classes were synthesised from first principles based on Levanon's derivations, implemented in Python without relying on any external DSP libraries.
